package random_username

var Adjectives = []string{
	"abundant", "acidic", "acoustic", "active", "actual", "adamant", "adaptable", "addicted", "adept", "administrative",
	"admirable", "advanced", "adventurous", "aeolian", "aerial", "aesthetic", "affable", "affected", "affectionate",
	"affirmative", "affordable", "afraid", "aged", "ageless", "aggressive", "agile", "agonizing", "agreeable", "aimless",
	"alert", "algebraic", "alien", "alive", "alluring", "altruistic", "amazing", "ambitious", "amenable", "amiable", "amicable",
	"amusing", "analogue", "ancient", "angelic", "angry", "anguished", "animated", "annoyed", "annual", "anxious", "apologetic",
	"appetizing", "appreciative", "apprehensive", "approachable", "appropriate", "arbitrary", "archaic", "ardent", "arid", "aromatic",
	"arrogant", "artful", "artificial", "artistic", "ashamed", "assertive", "assiduous", "athletic", "atmospheric", "atrocious",
	"attentive", "audacious", "authentic", "authoritarian", "automatic", "available", "average", "avid", "awake", "aware", "awesome",
	"awful", "awkward", "axiomatic", "azure", "balanced", "barbaric", "bashful", "basic", "beautiful", "belated", "belligerent",
	"beneficial", "benevolent", "berserk", "best", "bewildered", "big", "bitter", "bizarre", "black", "bland", "blank", "blaring",
	"bleak", "blind", "blissful", "blond", "blue", "blushing", "boiling", "bold", "bony", "boring", "bossy", "bouncy", "boundless",
	"brainy", "brash", "brave", "brawny", "breakable", "breezy", "brief", "bright", "brilliant", "brisk", "broad", "broken", "bronze",
	"brown", "bruised", "bubbly", "bulky", "bumpy", "buoyant", "burdensome", "burly", "bustling", "busy", "buttery", "buzzing",
	"calculating", "calm", "candid", "canine", "capable", "capital", "capricious", "careful", "careless", "caring", "cautious",
	"ceaseless", "celestial", "central", "cerebral", "certain", "changeable", "chaotic", "charismatic", "cheap", "cheerful",
	"chemical", "chief", "childlike", "chilly", "chivalrous", "choice", "chubby", "chunky", "circular", "civil", "clammy", "classic",
	"clean", "clear", "clever", "clinical", "closed", "cloudy", "clueless", "clumsy", "cluttered", "coarse", "coherent", "cold",
	"colorful", "colossal", "combative", "comfortable", "common", "compact", "competent", "complete", "complex", "complicated",
	"composed", "comprehensive", "concave", "concerned", "concrete", "condemned", "condescending", "confident", "confused",
	"congruent", "conscious", "constant", "content", "conventional", "convincing", "convoluted", "cool", "cooperative", "coordinated",
	"corny", "corrupt", "costly", "courageous", "courteous", "cowardly", "cozy", "crabby", "cracked", "crafty", "crazy", "creamy",
	"creative", "credible", "creepy", "critical", "crimson", "crooked", "crowded", "cruel", "crushing", "cuddly", "cultural",
	"cultured", "cumbersome", "curious", "curly", "current", "curt", "curved", "cute", "cynical", "damaged", "damp", "dangerous",
	"daring", "dark", "dazzling", "dead", "deadly", "deafening", "dear", "decent", "decisive", "decorous", "deep", "defeated",
	"defennial", "defensive", "defiant", "definite", "definitive", "delayed", "delectable", "delicious", "delightful", "delirious",
	"demanding", "dense", "dental", "dependable", "dependent", "descriptive", "deserted", "detailed", "determined", "devoted",
	"different", "difficult", "digital", "diligent", "dim", "dimpled", "dimwitted", "direct", "disastrous", "discrete", "distinct",
	"distorted", "dizzy", "dopey", "doting", "double", "drab", "dramatic", "dreary", "dry", "dual", "dull", "dusty", "dynamic",
	"eager", "early", "earnest", "earthy", "easy", "eccentric", "economic", "ecstatic", "edible", "educated", "effective", "efficient",
	"elaborate", "elastic", "elated", "elderly", "electric", "elegant", "elementary", "elliptical", "embarrassed", "embellished",
	"eminent", "emotional", "empty", "enchanted", "enchanting", "encouraging", "endurable", "energetic", "enlightened", "enormous",
	"enraged", "entire", "envious", "equal", "equatorial", "erratic", "essential", "esteemed", "ethical", "euphoric", "evanescent",
	"evasive", "even", "evergreen", "everlasting", "evil", "exalted", "excellent", "excited", "exciting", "exemplary", "exhausted",
	"exotic", "expensive", "experienced", "expert", "extraneous", "extroverted", "fabulous", "failing", "faint", "fair", "faithful",
	"fake", "false", "familiar", "famous", "fancy", "fantastic", "far", "fascinated", "fast", "fat", "fatal", "fatherly", "faulty",
	"favorable", "favorite", "fearful", "fearless", "feisty", "feline", "female", "feminine", "fertile", "festive", "few", "fickle",
	"fierce", "filthy", "fine", "finished", "firm", "first", "firsthand", "fitting", "fixed", "flaky", "flamboyant", "flashy", "flat",
	"flawed", "flawless", "flickering", "flimsy", "flippant", "flowery", "fluffy", "fluid", "flustered", "focused", "fond", "foolhardy",
	"foolish", "forceful", "forked", "formal", "forsaken", "forthright", "fortunate", "fragrant", "frail", "frank", "frayed", "free",
	"french", "frequent", "fresh", "friendly", "frightened", "frightening", "frigid", "frilly", "frivolous", "frizzy", "front",
	"frosty", "frozen", "frugal", "fruitful", "full", "fumbling", "functional", "funny", "fussy", "fuzzy", "gargantuan", "garrulous",
	"general", "generous", "gentle", "genuine", "giant", "giddy", "gigantic", "gifted", "giving", "glamorous", "glaring", "glass",
	"gleaming", "gleeful", "glimmering", "glittering", "gloomy", "glorious", "glossy", "glum", "golden", "good", "gorgeous",
	"graceful", "gracious", "grand", "grandiose", "granular", "grateful", "grave", "gray", "great", "greedy", "green", "gregarious",
	"grim", "grimy", "gripping", "grizzled", "gross", "grotesque", "grouchy", "grounded", "growing", "growling", "grown", "grubby",
	"gruesome", "grumpy", "guilty", "gullible", "gummy", "hairy", "half", "handmade", "handsome", "handy", "happy", "hard", "harmful",
	"harmless", "harmonious", "harsh", "hasty", "hateful", "haunting", "healthy", "heartfelt", "hearty", "heavenly", "heavy", "hefty",
	"helpful", "helpless", "hidden", "hideous", "high", "hilarious", "hoarse", "hollow", "homely", "honest", "honorable", "honored",
	"hopeful", "horrible", "hospitable", "hot", "huge", "humble", "humiliating", "humming", "humongous", "hungry", "hurtful", "husky",
	"icky", "icy", "ideal", "idealistic", "identical", "idle", "idiotic", "idolized", "ignorant", "ill", "illegal", "illiterate",
	"illustrious", "imaginary", "imaginative", "immaculate", "immaterial", "immediate", "immense", "impartial", "impassioned",
	"impeccable", "imperfect", "imperturbable", "impish", "impolite", "important", "impossible", "impractical", "impressionable",
	"impressive", "improbable", "impure", "inborn", "incomparable", "incompatible", "incomplete", "inconsequential", "incredible",
	"indelible", "indolent", "inexperienced", "infamous", "infantile", "infatuated", "inferior", "infinite", "informal", "innocent",
	"insecure", "insidious", "insignificant", "insistent", "instructive", "insubstantial", "intelligent", "intent", "intentional",
	"interesting", "internal", "international", "intrepid", "ironclad", "irresponsible", "irritating", "itchy", "jaded", "jagged",
	"jam-packed", "jaunty", "jealous", "jittery", "joint", "jolly", "jovial", "joyful", "joyous", "jubilant", "judicious", "juicy",
	"jumbo", "junior", "jumpy", "juvenile", "kaleidoscopic", "keen", "key", "kind", "kindhearted", "kindly", "klutzy", "knobby",
	"knotty", "knowing", "knowledgeable", "known", "kooky", "kosher", "lame", "lanky", "large", "last", "lasting", "late", "lavish",
	"lawful", "lazy", "leading", "lean", "leafy", "left", "legal", "legitimate", "light", "lighthearted", "likable", "likely",
	"limited", "limp", "limping", "linear", "lined", "liquid", "little", "live", "lively", "livid", "loathsome", "lone", "lonely",
	"long", "loose", "lopsided", "lost", "loud", "lovable", "lovely", "loving", "low", "loyal", "lucky", "lumbering", "luminous",
	"lumpy", "lustrous", "luxurious", "mad", "made-up", "magnificent", "majestic", "major", "male", "mammoth", "married", "marvelous",
	"masculine", "massive", "mature", "meager", "mealy", "mean", "measly", "meaty", "medical", "mediocre", "medium", "meek", "mellow",
	"melodic", "memorable", "menacing", "merry", "messy", "metallic", "mighty", "mild", "milky", "mindless", "miniature", "minor",
	"minty", "miserable", "miserly", "misguided", "misty", "mixed", "modern", "modest", "moist", "monstrous", "monthly", "monumental",
	"moral", "mortified", "motherly", "motionless", "mountainous", "muddy", "muffled", "multicolored", "mundane", "murky", "mushy",
	"musty", "muted", "mysterious", "naive", "narrow", "nasty", "natural", "naughty", "nautical", "near", "neat", "necessary", "needy",
	"negative", "neglected", "negligible", "neighborly", "nervous", "new", "next", "nice", "nifty", "nimble", "nippy", "nocturnal",
	"noisy", "nonstop", "normal", "notable", "noted", "noteworthy", "novel", "noxious", "numb", "nutritious", "nutty", "obedient",
	"obese", "oblong", "obvious", "occasional", "odd", "oddball", "offbeat", "offensive", "official", "oily", "old", "old-fashioned",
	"only", "open", "optimal", "optimistic", "opulent", "orange", "orderly", "organic", "ornate", "ornery", "ordinary", "original",
	"other", "our", "outlying", "outgoing", "outlandish", "outrageous", "outstanding", "oval", "overcooked", "overdue", "overjoyed",
	"overlooked", "palatable", "pale", "paltry", "parallel", "parched", "partial", "passionate", "past", "pastel", "peaceful",
	"peppery", "perfect", "perfumed", "periodic", "perky", "permanent", "perpetual", "perplexed", "personal", "pertinent", "pesky",
	"pessimistic", "petty", "phony", "physical", "piercing", "pink", "pitiful", "plain", "plaintive", "plastic", "playful",
	"pleasant", "pleased", "pleasing", "plump", "plush", "polished", "polite", "political", "pointed", "pointless", "poised",
	"poor", "popular", "portly", "posh", "positive", "possible", "potable", "powerful", "powerless", "practical", "precious",
	"present", "prestigious", "pretty", "previous", "pricey", "prickly", "primary", "prime", "pristine", "private", "prize",
	"probable", "productive", "profitable", "profuse", "proper", "proud", "prudent", "punctual", "pungent", "puny", "pure", "purple",
	"pushy", "putrid", "puzzled", "quaint", "qualified", "quarrelsome", "quarterly", "queasy", "querulous", "questionable", "quick",
	"quiet", "quintessential", "quirky", "quixotic", "quizzical", "radiant", "ragged", "rapid", "rare", "rash", "raw", "ready",
	"real", "realistic", "reasonable", "recent", "reckless", "rectangular", "red", "redundant", "reflecting", "regal", "regular",
	"reliable", "relieved", "remarkable", "remorseful", "remote", "repentant", "repulsive", "required", "respectful", "responsible",
	"revolving", "rewarding", "rich", "rigid", "right", "ringed", "ripe", "roasted", "robust", "rosy", "rotating", "rotten", "rough",
	"round", "rowdy", "royal", "rubbery", "ruddy", "rude", "rundown", "runny", "rural", "rusty", "sad", "safe", "salty", "same",
	"sandy", "sane", "sarcastic", "sardonic", "satisfied", "scaly", "scarce", "scared", "scary", "scented", "scholarly", "scientific",
	"scornful", "scratchy", "scrawny", "second", "secondary", "secret", "self-assured", "self-reliant", "selfish", "sentimental",
	"separate", "serene", "serious", "serpentine", "several", "severe", "shabby", "shadowy", "shady", "shallow", "shameful",
	"shameless", "sharp", "shimmering", "shiny", "shocked", "shocking", "shoddy", "short", "showy", "shrill", "shy", "sick",
	"silent", "silky", "silly", "silver", "similar", "simple", "simplistic", "sinful", "single", "sizzling", "skeletal", "skinny",
	"sleepy", "slight", "slim", "slimy", "slippery", "slow", "slushy", "small", "smart", "smoggy", "smooth", "smug", "snappy",
	"snarling", "sneaky", "sniveling", "snoopy", "sociable", "soft", "soggy", "solid", "somber", "some", "sophisticated", "sore",
	"sorrowful", "soulful", "soupy", "sour", "spanish", "sparkling", "sparse", "specific", "spectacular", "speedy", "spherical",
	"spicy", "spiffy", "spirited", "spiteful", "splendid", "spotless", "spotted", "spry", "square", "squeaky", "squiggly", "stable",
	"staid", "stained", "stale", "standard", "starchy", "stark", "starry", "steep", "sticky", "stiff", "stimulating", "stingy",
	"stormy", "straight", "strange", "steel", "strict", "strident", "striking", "striped", "strong", "studious", "stunning",
	"stupendous", "stupid", "sturdy", "stylish", "subdued", "submissive", "substantial", "subtle", "suburban", "sudden", "sugary",
	"sunny", "super", "superb", "superficial", "superior", "supportive", "sure-footed", "surprised", "suspicious", "svelte",
	"sweaty", "sweet", "swift", "sympathetic", "tall", "tame", "tan", "tangible", "tart", "tasty", "tattered", "taut", "tedious",
	"teeming", "tempting", "tender", "tense", "tepid", "terrible", "terrific", "testy", "thankful", "that", "these", "thick",
	"thin", "third", "thirsty", "this", "thorny", "thorough", "those", "thoughtful", "threadbare", "thrifty", "thunderous", "tidy",
	"tight", "timely", "tinted", "tiny", "tired", "torn", "total", "tough", "tragic", "trained", "traumatic", "treasured",
	"remendous", "triangular", "tricky", "trifling", "trim", "trivial", "troubled", "true", "trusting", "trustworthy", "trusty",
	"truthful", "tubby", "turbulent", "twin", "ugly", "ultimate", "unacceptable", "unaware", "uncomfortable", "uncommon",
	"unconscious", "understated", "unequaled", "uneven", "unfinished", "unfit", "unfolded", "unfortunate", "unhappy", "unhealthy",
	"uniform", "unimportant", "unique", "united", "unkempt", "unknown", "unlawful", "unlined", "unlucky", "unnatural", "unpleasant",
	"unrealistic", "unripe", "unruly", "unselfish", "unsightly", "unsteady", "unsung", "untidy", "untimely", "untried", "untrue",
	"unused", "unusual", "unwelcome", "unwieldy", "unwilling", "unwitting", "unwritten", "upbeat", "upright", "upset", "urban",
	"usable", "used", "useful", "useless", "utilized", "utter", "vacant", "vague", "vain", "valid", "valuable", "vapid", "variable",
	"vast", "velvety", "venerated", "vengeful", "verifiable", "vibrant", "vicious", "victorious", "vigilant", "vigorous",
	"villainous", "violet", "violent", "virtual", "virtuous", "visible", "vital", "vivacious", "vivid", "voluminous", "wan",
	"warlike", "warm", "warmhearted", "warped", "wary", "wasteful", "watchful", "waterlogged", "watery", "wavy", "weak", "wealthy",
	"weary", "webbed", "wee", "weekly", "weepy", "weighty", "weird", "welcome", "wet", "which", "whimsical", "whirlwind", "whispered",
	"white", "whole", "whopping", "wicked", "wide", "wide-eyed", "wiggly", "wild", "willing", "wilted", "winding", "windy", "winged",
	"wiry", "wise", "witty", "wobbly", "woeful", "wonderful", "wooden", "woozy", "wordy", "worldly", "worn", "worried", "worrisome",
	"worse", "worst", "worthless", "worthwhile", "worthy", "wrathful", "wretched", "writhing", "wrong", "wry", "yawning", "yearly",
	"yellow", "yellowish", "young", "youthful", "yummy", "zany", "zealous", "zesty", "zigzag",
}
