package random_username

var Nouns = []string{
	"aardvark", "aardwolf", "abalone", "addax", "adder", "agouti", "akita", "albatross", "alligator", "alpaca", "amoeba",
	"amphibian", "anaconda", "anchovy", "angelfish", "ani", "anole", "ant", "anteater", "antelope", "ape", "aphid", "arachnid",
	"armadillo", "asp", "ass", "auk", "avocet", "axolotl", "baboon", "badger", "bandicoot", "barb", "barnacle", "barracuda",
	"basenji", "basilisk", "bass", "bat", "beagle", "bear", "beaver", "bee", "beetle", "binturong", "bird", "bison", "bittern",
	"blackbird", "bloodhound", "bluebird", "bluegill", "boa", "boar", "bobcat", "bobolink", "bonito", "bonobo", "booby", "borzoi",
	"boxer", "bream", "briard", "brill", "buck", "budgerigar", "buffalo", "bug", "bulbul", "bull", "bulldog", "bullfrog", "bullhead",
	"bumblebee", "bunting", "burbot", "bustard", "butterfly", "buzzard", "caddisfly", "caiman", "calf", "camel", "canary", "capybara",
	"caracal", "cardinal", "caribou", "carp", "cassowary", "cat", "catbird", "caterpillar", "catfish", "cattle", "cavy", "centipede",
	"chameleon", "chamois", "char", "cheetah", "chickadee", "chicken", "chihuahua", "chimpanzee", "chinchilla", "chipmunk", "chiton",
	"chow", "chub", "cicada", "cichlid", "civet", "clam", "coati", "cobra", "cockatoo", "cockle", "cockroach", "cod", "coelacanth",
	"collie", "colt", "conch", "condor", "conger", "coot", "copepod", "copperhead", "coral", "corgi", "cormorant", "cougar", "cow",
	"cowbird", "cowrie", "coyote", "crab", "crake", "crane", "crappie", "crayfish", "creeper", "cricket", "crocodile", "crossbill",
	"crow", "cuckoo", "curlew", "cuscus", "cuttlefish", "dab", "dace", "dachshund", "dalmatian", "damselfly", "danio", "darter",
	"deer", "degu", "dhole", "dickcissel", "dingo", "dinosaur", "dipper", "discus", "doberman", "dodo", "doe", "dog", "dogfish",
	"dolphin", "donkey", "dorado", "dormouse", "dotterel", "dove", "dowitcher", "dragonfly", "drake", "dromedary", "drongo", "drum",
	"duck", "dugong", "dunlin", "dunnart", "eagle", "earthworm", "earwig", "echidna", "eel", "egret", "eider", "eland", "elephant",
	"elk", "emu", "ermine", "ewe", "falcon", "ferret", "finch", "firefly", "fish", "fisher", "flamingo", "flea", "flicker", "flounder",
	"fly", "flycatcher", "foal", "fossa", "owl", "fox", "frigatebird", "frog", "frogmouth", "gadwall", "galago", "gannet", "gar",
	"garfish", "garganey", "gaur", "gazelle", "gecko", "gelada", "gemsbok", "genet", "gerbil", "gharial", "gibbon", "giraffe", "glider",
	"gnat", "gnu", "goat", "goby", "godwit", "goldfish", "goose", "gopher", "gorilla", "goshawk", "gourami", "grackle", "grasshopper",
	"grayling", "grebe", "greyhound", "grosbeak", "groundhog", "grouper", "grouse", "grunt", "guanaco", "guillemot", "guineafowl",
	"gull", "guppy", "gyrfalcon", "haddock", "hagfish", "hake", "halibut", "hamster", "hare", "harrier", "hartebeest", "havanese",
	"hawk", "hedgehog", "heifer", "hen", "heron", "herring", "hippo", "hippopotamus", "hoatzin", "hog", "hoki", "honeycreeper",
	"hoopoe", "hornbill", "hornet", "horse", "human", "hummingbird", "husky", "hydra", "hyena", "hyrax", "ibex", "ibis", "iguana",
	"impala", "indri", "insect", "isopod", "jacana", "jack", "jackal", "jaeger", "jaguar", "jay", "jellyfish", "junco", "kangaroo",
	"keeshond", "kestrel", "kid", "killdeer", "kingbird", "kingfisher", "kinglet", "kinkajou", "kite", "kitten", "kittiwake", "kiwi",
	"knot", "koala", "kob", "koi", "komondor", "krill", "kudu", "kuvasz", "ladybug", "lamb", "lamprey", "langur", "lapwing", "lark",
	"leafhopper", "leech", "lemming", "lemur", "leopard", "liger", "limpet", "ling", "lion", "lizard", "llama", "loach", "lobster",
	"locust", "loon", "lorikeet", "loris", "louse", "lovebird", "lungfish", "lynx", "macaque", "macaw", "mackerel", "maggot",
	"magpie", "mahseer", "malamute", "mallard", "mamba", "mammoth", "manatee", "mandrill", "manta", "mantis", "mare", "marlin",
	"marmoset", "marmot", "marten", "martin", "mastiff", "mastodon", "mayfly", "meerkat", "merganser", "merlin", "midge", "millipede",
	"mink", "minnow", "mite", "mockingbird", "mole", "mollusk", "molly", "mongoose", "monitor", "monkey", "moorhen", "moose",
	"mosquito", "moth", "mouse", "mudskipper", "mule", "mullet", "muntjac", "murre", "murrelet", "muskox", "muskrat", "mussel",
	"myna", "narwhal", "nautilus", "nematode", "nene", "newfoundland", "newt", "nightingale", "nightjar", "numbat", "nutcracker",
	"nuthatch", "nutria", "nyala", "ocelot", "octopus", "okapi", "onager", "opossum", "orangutan", "orca", "oriole", "oryx", "oscar",
	"osprey", "ostrich", "otter", "ovenbird", "ox", "oyster", "paca", "pachyderm", "pademelon", "panda", "pangolin", "panther",
	"papillon", "parakeet", "parrot", "partridge", "peacock", "peafowl", "peccary", "pekingese", "pelican", "penguin", "perch",
	"petrel", "phalarope", "pheasant", "phoebe", "pig", "pigeon", "pika", "pike", "pilchard", "pinniped", "pintail", "pipit", "piranha",
	"plaice", "planarian", "platypus", "plover", "pointer", "polecat", "pollack", "pollock", "pomeranian", "pony", "pooch", "poodle",
	"porcupine", "porpoise", "possum", "potoroo", "prawn", "primate", "pronghorn", "ptarmigan", "puffer", "puffin", "pug", "puli",
	"puma", "pupa", "pup", "puppy", "python", "quagga", "quail", "quetzal", "quokka", "quoll", "rabbit", "raccoon", "rail", "ram",
	"rasbora", "rat", "rattlesnake", "raven", "ray", "razorbill", "redhead", "redpoll", "redstart", "reindeer", "rhea", "rhino",
	"rhinoceros", "roach", "roadrunner", "robin", "roebuck", "roller", "rooster", "rottweiler", "rudd", "ruff", "sable", "saiga",
	"saki", "salamander", "salmon", "saluki", "samoyed", "sanderling", "sandpiper", "sapsucker", "sardine", "sawfish", "scad",
	"scallop", "scaup", "schipperke", "schnauzer", "scorpion", "scoter", "screamer", "seagull", "seahorse", "seal", "serval", "setter",
	"shad", "shark", "shearwater", "sheep", "sheepdog", "shelduck", "shiba", "shoveler", "shrew", "shrike", "shrimp", "siamang",
	"sidewinder", "sifaka", "siskin", "skate", "skimmer", "skink", "skipper", "skua", "skunk", "skylark", "sloth", "slug", "smelt",
	"smew", "snail", "snake", "snapper", "snipe", "snook", "solenodon", "sole", "sora", "sow", "spaniel", "sparrow", "spider", "spitz",
	"sponge", "spoonbill", "sprat", "springbok", "squid", "squirrel", "stag", "stallion", "starfish", "starling", "steer", "stickbug",
	"stilt", "stingray", "stoat", "stork", "sturgeon", "sucker", "sunfish", "swallow", "swan", "swift", "swine", "swordfish",
	"tadpole", "taipan", "takin", "tamandua", "tamarin", "tanager", "tapir", "tarantula", "tarpon", "tarsier", "tayra", "teal",
	"tegu", "tench", "tenrec", "tern", "terrapin", "terrier", "tetra", "thrasher", "thrips", "thrush", "tiger", "tilapia", "tinamou",
	"tit", "titmouse", "toad", "topi", "tortoise", "toucan", "towhee", "tragopan", "trogon", "trout", "tuatara", "tuna", "turbot",
	"turkey", "turnstone", "turtle", "uakari", "urchin", "veery", "verdin", "vicuna", "viper", "ireo", "vizsla", "vole", "vulture",
	"wagtail", "wahoo", "wallaby", "wallaroo", "walleye", "walrus", "wapiti", "warbler", "warthog", "wasp", "waterthrush", "waxwing",
	"weasel", "weaver", "weevil", "weimaraner", "weta", "whale", "wheatear", "whelk", "whimbrel", "whippet", "whitefish", "whiting",
	"widgeon", "wildebeest", "willet", "wolf", "wolverine", "wombat", "woodchuck", "woodcock", "woodpecker", "worm", "wrasse", "wren",
	"wryneck", "yak", "yellowlegs", "zander", "zebra", "zebu", "zorilla",
}
